/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.imagepicker;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiActivitySupport;
import org.appcelerator.titanium.util.TiActivityResultHandler;
import org.appcelerator.titanium.TiBlob;

import android.annotation.TargetApi;
import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.media.ExifInterface;

import java.util.ArrayList;
import java.util.List;
import java.io.IOException;

import com.zhihu.matisse.Matisse;

@Kroll.module(name="TitaniumImagepicker", id="ti.imagepicker")
public class TitaniumImagepickerModule extends KrollModule implements TiActivityResultHandler {
	private static final String LCAT = "TitaniumImagepickerModule";
	private KrollFunction callback;
	protected int requestCode;

	@Kroll.method(runOnUiThread = true)
	public void openGallery(KrollDict args) {
		callback = (KrollFunction) args.get("callback");
		
		int maxImageSelection = args.optInt(Defaults.PROPERTY_MAX_IMAGE_SELECTION, Defaults.VALUE_MAX_IMAGE_SELECTION);

		Activity activity = TiApplication.getInstance().getCurrentActivity();
		TiActivitySupport support = (TiActivitySupport) activity;
		requestCode = support.getUniqueResultCode();		
		
		Intent matisseIntent = new Intent(activity, TiMatisseActivity.class);
		matisseIntent.putExtra(Defaults.PROPERTY_MAX_IMAGE_SELECTION, maxImageSelection);
		
		support.launchActivityForResult(matisseIntent, requestCode, this);
	}

	@TargetApi(Build.VERSION_CODES.HONEYCOMB)
	@Override
	public void onResult(Activity activity, int thisRequestCode, int resultCode, Intent data) {
		if (callback == null) return;
		
		final KrollDict event = new KrollDict();

		if (thisRequestCode == requestCode && data != null) {
			event.put(Defaults.CALLBACK_PROPERTY_SUCCESS, true);
			event.put(Defaults.CALLBACK_PROPERTY_CANCEL, false);

			final List<Uri> paths = Matisse.obtainResult(data);
			final ArrayList<TiBlob> blobList = new ArrayList<>();

			for (Uri url : paths) {
				ExifInterface exif = null;
				String realUrl = Utils.getFilePath(url, TiApplication.getInstance().getApplicationContext());

				try {
					exif = new ExifInterface(realUrl);
				} catch (IOException e) {
					e.printStackTrace();
				}

				int orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, 1);
				TiBlob blob = TiBlob.blobFromImage(Utils.getFixBitMapFromFile(realUrl, orientation));

				blobList.add(blob);
			}

			if (paths != null) {
				event.put(Defaults.CALLBACK_PROPERTY_IMAGES, blobList.toArray());
			} else {
				event.put(Defaults.CALLBACK_PROPERTY_IMAGES, new Object[0]);
			}
		} else {
			event.put(Defaults.CALLBACK_PROPERTY_SUCCESS, false);
			event.put(Defaults.CALLBACK_PROPERTY_CANCEL, true);
			event.put(Defaults.CALLBACK_PROPERTY_IMAGES, new Object[0]);
		}
		
		callback.callAsync(getKrollObject(), event);
	}

	@Override
	public void onError(Activity activity, int requestCode, Exception e) {
		if (callback == null) return;

		KrollDict event = new KrollDict();
		event.put(Defaults.CALLBACK_PROPERTY_SUCCESS, false);
		callback.callAsync(getKrollObject(), event);
	}
}

